function [u,v,pw,x,y] = solution(x,y)
%SOLUTION
%    [U,V,PW,X,Y] = SOLUTION(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Mar-2022 11:24:39

u = 0.0;
if nargout > 1
    v = 0.0;
end
if nargout > 2
    pw = y.^3.*(y-1.0).^2.*1.0e+3;
end
if nargout > 3
    x = x;
end
if nargout > 4
    y = y;
end
