function [f,x,y] = sourceWP(x,y)
%SOURCEWP
%    [F,X,Y] = SOURCEWP(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Mar-2022 11:24:40

t2 = y-1.0;
f = t2.*y.^2.*1.2e+4+t2.^2.*y.*6.0e+3+y.^3.*2.0e+3;
if nargout > 1
    x = x;
end
if nargout > 2
    y = y;
end
