function [f,x,y] = sourceWP(x,y)
%SOURCEWP
%    [F,X,Y] = SOURCEWP(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Mar-2022 09:55:28

f = 0.0;
if nargout > 1
    x = x;
end
if nargout > 2
    y = y;
end
