function [normP,x1,x3] = ErrorNormP(x1,x3,pw1,pw2)
%ERRORNORMP
%    [NORMP,X1,X3] = ERRORNORMP(X1,X3,PW1,PW2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2022 17:18:39

t2 = x1.^2;
t3 = x1.^3;
t4 = x3.^2;
t5 = x3.^3;
normP = (x1-x3).*(t2.*1.0e+1-t3.*1.5e+1+t4.*1.0e+1-t5.*1.5e+1+pw1.*pw2.*1.0e+1-pw1.*t2.*1.5e+1-pw2.*t2.*5.0-pw1.*t4.*5.0-pw2.*t4.*1.5e+1+t2.*t4.*6.0+pw1.*x1.*2.0e+1+pw2.*x1.*1.0e+1+pw1.*x3.*1.0e+1+pw2.*x3.*2.0e+1-t2.*x3.*1.5e+1-t4.*x1.*1.5e+1+t3.*x3.*6.0+t5.*x1.*6.0+x1.*x3.*1.0e+1+pw1.^2.*1.0e+1+pw2.^2.*1.0e+1+t2.^2.*6.0+t4.^2.*6.0-pw1.*x1.*x3.*1.0e+1-pw2.*x1.*x3.*1.0e+1).*(-1.0./3.0e+1);
if nargout > 1
    x1 = x1;
end
if nargout > 2
    x3 = x3;
end
