function [out1,x,y] = source(x,y)
%SOURCE
%    [OUT1,X,Y] = SOURCE(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    14-Mar-2022 11:24:39

out1 = [0.0;0.0];
if nargout > 1
    x = x;
end
if nargout > 2
    y = y;
end
