function [out1,x1,x3] = f1X(x1,x3)
%F1X
%    [OUT1,X1,X3] = F1X(X1,X3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2022 17:18:38

t2 = x1.^2;
t3 = x1.^3;
t4 = x3.^2;
t5 = x3.^3;
t6 = x1.*(7.0./2.0);
t7 = x3.*(7.0./2.0);
t9 = x1.*x3.*(6.1e+1./3.0);
t8 = -t6;
out1 = [t2.*(6.1e+1./3.0)-t3.*1.8e+1-t5.*2.0+t7+t8-t9+t2.*x3.*1.4e+1+t4.*x1.*6.0;t3.*2.0-t4.*(6.1e+1./3.0)+t5.*1.8e+1+t7+t8+t9-t2.*x3.*6.0-t4.*x1.*1.4e+1;t2.*(1.22e+2./3.0)-t3.*2.4e+1-t4.*(1.22e+2./3.0)+t5.*2.4e+1-x1.*1.4e+1+x3.*1.4e+1-t2.*x3.*8.0+t4.*x1.*8.0];
if nargout > 1
    x1 = x1;
end
if nargout > 2
    x3 = x3;
end
