function [u,v,pw,x,y] = solution(x,y)
%SOLUTION
%    [U,V,PW,X,Y] = SOLUTION(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Mar-2022 09:55:27

u = 0.0;
if nargout > 1
    t2 = y.^3;
    t3 = y-1.0;
    t4 = t3.^2;
    v = (t2.*t4)./1.0e+2;
end
if nargout > 2
    pw = t2.*t3.*(5.0./3.0)+t4.*y.^2.*(5.0./2.0);
end
if nargout > 3
    x = x;
end
if nargout > 4
    y = y;
end
