function [out1,x,y] = source(x,y)
%SOURCE
%    [OUT1,X,Y] = SOURCE(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Mar-2022 09:34:43

t2 = y-1.0;
out1 = [0.0;t2.^2.*y.^2.*(-2.1e+2./1.3e+1)-t2.*y.^3.*(2.8e+2./1.3e+1)-y.^4.*(3.5e+1./1.3e+1)];
if nargout > 1
    x = x;
end
if nargout > 2
    y = y;
end
