function fTerm2 = f2(x1,x3)
%F2
%    FTERM2 = F2(X1,X3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Mar-2022 15:55:08

t2 = x1.^2;
t3 = x1.^3;
t4 = x3.^2;
t5 = x3.^3;
t6 = x1.*(3.0./2.0);
t7 = x3.*(3.0./2.0);
t8 = (x1.*x3)./3.0;
t9 = (t4.*x1)./4.0;
t10 = (t2.*x3)./4.0;
fTerm2 = [t2./3.0+t3./4.0-t4.*(2.0./3.0)-t5.*(3.0./4.0)-t6+t7+t8+t9+t10,t2.*(-2.0./3.0)-t3.*(3.0./4.0)+t4./3.0+t5./4.0+t6-t7+t8+t9+t10];
