function [out1,x1,x3] = f2X(x1,x3)
%F2X
%    [OUT1,X1,X3] = F2X(X1,X3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2022 17:18:38

t2 = x1.^2;
t3 = x1.^3;
t5 = x3.^2;
t6 = x3.^3;
t8 = (x1.*x3)./3.0;
t14 = x1./1.0e+5;
t15 = x3./1.0e+5;
t4 = t2.^2;
t7 = t5.^2;
t9 = (t5.*x1)./2.0;
t10 = (t2.*x3)./2.0;
t11 = (t6.*x1)./5.0;
t12 = (t3.*x3)./5.0;
t13 = (t2.*t5)./5.0;
t16 = -t14;
out1 = [t2.*(-2.0./3.0)+t3.*(3.0./2.0)-t4.*(4.0./5.0)+t5./3.0-t6./2.0+t7./5.0+t8-t9-t10+t11+t12+t13+t15+t16;t2.*(-1.0./3.0)+t3./2.0-t4./5.0+t5.*(2.0./3.0)-t6.*(3.0./2.0)+t7.*(4.0./5.0)-t8+t9+t10-t11-t12-t13+t15+t16];
if nargout > 1
    x1 = x1;
end
if nargout > 2
    x3 = x3;
end
