function [u,x1,x3] = SolutionU(x,x1,x3)
%SOLUTIONU
%    [U,X1,X3] = SOLUTIONU(X,X1,X3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2022 17:18:37

u = x.^2.*(x-1.0).^2;
if nargout > 1
    x1 = x1;
end
if nargout > 2
    x3 = x3;
end
