function [p,x1,x3] = SolutionP(x,x1,x3)
%SOLUTIONP
%    [P,X1,X3] = SOLUTIONP(X,X1,X3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Mar-2022 17:18:37

p = x.*(x-1.0);
if nargout > 1
    x1 = x1;
end
if nargout > 2
    x3 = x3;
end
